services:
  batchprocessing:
    build:
      context: .
      dockerfile: BatchProcessing/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

  iplookup:
    build:
      context: .
      dockerfile: IPLookup/Dockerfile
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090